### ISSUE TITLE
Net::HTTPNotFound for http://www.muswellbrook.nsw.gov.au/index.php/search-development-applications

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/muswellbrook#2]
```
Injecting configuration and compiling...
 Injecting scraper and running...
 /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch' :  404 => Net::HTTPNotFound for http://www.muswellbrook.nsw.gov.au/index.php/search-development-applications -- unhandled response  ( Mechanize::ResponseCodeError )
    from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
    from scraper.rb:9:in `<main>'
```

Looks like http://datracker.muswellbrook.nsw.gov.au/Home/Disclaimer is the new home since Feb 2015 - looks like one of the common systems, can't tell which at first glance

**Comment by henare** [comment]
There's an ATDIS feed https://github.com/openaustralia/planningalerts/issues/920
